# Data Science Capstone Part B  
## Data
This project will source and integrate Foursquare data, as well as data from Wellbeing Toronto. 

### Wellbeing Toronto  
Wellbeing Toronto provides neighbourhood-level datasets about Toronto services, facilities, and well-being. The datasets are segmented by community indicators grouped under 11 categories, including demographics, civics, and health as examples. While primarily a mapping application, and underlying datasets are downloadable.  

For this project, the dataset of interest includes the Healthy Food Index and Total Population indicators for each of Toronto’s 140 neighbourhoods. These data are downloadable as a csv file, and include the neighbourhood name and number. Wellbeing Toronto is publicly accessible at https://map.toronto.ca/wellbeing.

#### Wellbeing Toronto data sample
Following is a sample of the imported data showing the populations and healthy food index for each neighbourhood:

In [2]:
import pandas as pd
import numpy as np

# use cleansed csv file
hlthdata ="wellbeing_toronto.csv"
dfhlt = pd.read_csv(hlthdata)    #df = pd.read_excel(PCodeData)  # use this for Excel file
dfhlt.drop(['Combined Indicators'], axis=1, inplace = True)
dfhlt.head()

,Neighbourhood,Neighbourhood Id,Total Population,Healthy Food Index
0,West Humber-Clairville,1.0,33312.0,23.82
1,Mount Olive-Silverstone-Jamestown,2.0,32954.0,37.57
2,Thistletown-Beaumond Heights,3.0,10360.0,42.26
3,Rexdale-Kipling,4.0,10529.0,23.31
4,Elms-Old Rexdale,5.0,9456.0,24.71

In [3]:
print('This dataframe has', dfhlt.shape[0], 'rows.')

This dataframe has 140 rows.

### Foursquare data  

Foursquare provides a mobile app that allows users to search for near-by venues and see information and reviews. Users also feed information back to Foursquare both passively, as the app tracks users’ locations, and actively as users enter venue names, locations, and reviews.  

Since 2009, users have provided Foursquare with location data on over 105 million venues, with “over 75 million tips from local experts.” As one of the largest sources of location-based venue data, the company describes itself as “a is a technology company that uses location intelligence to build meaningful consumer experiences and business solutions.” (3)  

This project will access Foursquare venue data for the selected “Wellbeing Toronto” neighbourhoods, specifically food venues. The Foursquare venue data will particularly seek to identify food venues that are categorized as most healthy and least healthy. These data will then be used for subsequent comparison and categorization to provide insight to the business problem.  

The Foursquare venue data are accessible via application programming interface (API). A free developer account is used to access the data from https://developer.foursquare.com/places-api.  

(3) Sourced from https://foursquare.com/about

#### Foursquare data sample
Following is a sample of the imported data showing particularly the venues (by name) and the respective venue categories:

In [13]:
fsqSam = pd.read_csv('4sqSample.csv')
#fsqSam.drop(['Unnamed: 0'], axis=1, inplace = True)
fsqSam.head(10)

,Neighbourhood,Neighbourhood Latitude,Neighbourhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Rosedale,43.679563,-79.377529,Rosedale Park,43.682328,-79.378934,Playground
1,Rosedale,43.679563,-79.377529,Whitney Park,43.682036,-79.373788,Park
2,Rosedale,43.679563,-79.377529,Alex Murray Parkette,43.678300,-79.382773,Park
3,Rosedale,43.679563,-79.377529,Milkman's Lane,43.676352,-79.373842,Trail
4,"Cabbagetown, St. James Town",43.667967,-79.367675,Cranberries,43.667843,-79.369407,Diner
5,"Cabbagetown, St. James Town",43.667967,-79.367675,F'Amelia,43.667536,-79.368613,Italian Restaurant
6,"Cabbagetown, St. James Town",43.667967,-79.367675,Butter Chicken Factory,43.667072,-79.369184,Indian Restaurant
7,"Cabbagetown, St. James Town",43.667967,-79.367675,Kingyo Toronto,43.665895,-79.368415,Japanese Restaurant
8,"Cabbagetown, St. James Town",43.667967,-79.367675,Murgatroid,43.667381,-79.369311,Restaurant
9,"Cabbagetown, St. James Town",43.667967,-79.367675,Cabbagetown Brew,43.666923,-79.369289,Café

#### End of Week 4 asssignment Part B